In [7]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

In [8]:
imdb = Table.read_table('imdb.csv')
imdb.show(5)

In [26]:
imdb.show(10)

In [40]:
Callie = make_array("Callie", "Oreo")
GoodDog = make_array (10,15)
Table().with_columns("Good Dog", GoodDog, "Name", Callie)

Good Dog | Name
10       | Callie
15       | Oreo

# Question 1
Find the ten movies released in the year 2000 or later with the highest number of votes according to imdb.csv. Format your answer as a table with columns Title and Votes (in that order) of the three requested movies.

In [9]:
movies2000 = imdb.where("Year", are.above_or_equal_to (2000))
movies2000votes = movies2000.sort("Votes", descending=True)
moviestop10 = movies2000votes.take(np.arange(10))
final_table = moviestop10.select("Title", "Votes")
final_table.show()

In [10]:
#movies2000 = imdb.where('Year', are.above_or_equal_to(2000))
#movies2000sorted = movies2000.sort('Votes', descending = True)
movies2000top10 = movies2000sorted.take(np.arange(0,10))
#moviesfinal = movies2000top10.select("Title", "Votes")
#moviesfinal.show()

In [23]:
movies2000 = imdb.where('Year', are.above_or_equal_to(2000))
movies2000sorted = movies2000.sort('Votes', descending = True)
movies2000top10 = movies2000sorted.take(np.arange(0,10))
movies2000top10

Votes   | Rating | Title                                             | Year | Decade
1473049 | 8.9    | The Dark Knight                                   | 2008 | 2000
1271949 | 8.7    | Inception                                         | 2010 | 2010
1099087 | 8.8    | The Lord of the Rings: The Fellowship of the Ring | 2001 | 2000
1074146 | 8.9    | The Lord of the Rings: The Return of the King     | 2003 | 2000
997350  | 8.4    | The Dark Knight Rises                             | 2012 | 2010
967389  | 8.7    | The Lord of the Rings: The Two Towers             | 2002 | 2000
862216  | 8.5    | Gladiator                                         | 2000 | 2000
862016  | 8      | The Avengers                                      | 2012 | 2010
850601  | 8.3    | Batman Begins                                     | 2005 | 2000
804729  | 8.4    | Django Unchained                                  | 2012 | 2010

In [19]:
item10=movies2000top10.take(9)
item10

Votes  | Rating | Title            | Year | Decade
804729 | 8.4    | Django Unchained | 2012 | 2010

# Question 2

Create a table with columns Title and Votes containing all movies released in 1999.

Next, attach a new column to the table called Percent Votes that contains the percent of votes each movie received when considered among all votes cast for movies released in 1999.

For example, if the total number of votes cast for movies released in 1999 is 200 and "The Matrix" received 30 of them, then the column Percent Votes corresponding to "The Matrix" should 15.

In [ ]:
movies1999 = imdb.where("Year", 1999)
movies1999 = movies1999.select('Title', 'Votes')
votes1999 = movies1999.column("Votes")
sumofvotes = sum(votes1999)
votes = votes1999/sumofvotes *100
new = movies1999.with_column("Percent Votes", votes)
new

Title           | Votes   | Percent Votes
Fight Club      | 1177098 | 27.4441
American Beauty | 735056  | 17.1379
The Sixth Sense | 630994  | 14.7117
The Matrix      | 1073043 | 25.0181
The Green Mile  | 672878  | 15.6882

In [ ]:
#movies1999 = imdb.where('Year', 1999)
#movies1999 = movies1999.select('Title', 'Votes')
#votes_column = movies1999.column('Votes')
#total_votes = sum(votes_column)
#percent_column = votes_column / total_votes * 100
#movies1999 = movies1999.with_column('Percent Votes', percent_column)
#movies1999.show()

NameError: name 'Table' is not defined