In [1]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## Columns of Tables are Arrays ##

In [2]:
nba = Table.read_table('nba_salaries.csv')
warriors = nba.where('team', 'Golden State Warriors')

In [3]:
warriors

rank | name              | position | team                  | salary  | season
41   | Donyell Marshall  | PF       | Golden State Warriors | 5250000 | 2000
47   | Erick Dampier     | C        | Golden State Warriors | 4988000 | 2000
58   | Mookie Blaylock   | G        | Golden State Warriors | 4200000 | 2000
59   | Chris Mills       | SF       | Golden State Warriors | 4200000 | 2000
64   | Jason Caffey      | F        | Golden State Warriors | 3937000 | 2000
89   | Vonteego Cummings | PG       | Golden State Warriors | 2600000 | 2000
92   | Antawn Jamison    | PF       | Golden State Warriors | 2503000 | 2000
73   | Erick Dampier     | C        | Golden State Warriors | 5611000 | 2001
91   | Mookie Blaylock   | G        | Golden State Warriors | 4800000 | 2001
92   | Chris Mills       | SF       | Golden State Warriors | 4800000 | 2001
... (301 rows omitted)

In [4]:
salary_select = warriors.select('salary')
salary_select

salary
5250000
4988000
4200000
4200000
3937000
2600000
2503000
5611000
4800000
4800000
... (301 rows omitted)

In [5]:
type(salary_select)
# Returns a column in a table format

datascience.tables.Table

In [6]:
salary_col = warriors.column('salary')
salary_col

array([ 5250000,  4988000,  4200000,  4200000,  3937000,  2600000,
        2503000,  5611000,  4800000,  4800000,  4386000,  3578000,
        3390000,  2678000,  1842000,   757000,   316000,   316000,
         241000,    32000,  6235000,  5400000,  5400000,  4913000,
        4441000,  4400000,  3388000,  3000000,  2343000,  2021000,
        1310000,   333000,   333000,  6858000,  6000000,  5540000,
        4935000,  4469000,  4400000,  1409000,   700000,   512000,
       10912000,  7482000,  5445000,  4400000,  1667000,  1507000,
        3000000,  2481000,  2390000,  2232000, 13700000,  8888888,
        7365079,  7312500,  5393300,  4506261,  1988160,  1910520,
        1857360,  1760000,  1404360,   448762,   423762, 15070000,
        9999999,  8125000,  2535260,  2157097,  2061720,  1986960,
         798112,   744551,   664209,   259770, 16440000,  8425625,
        6630000,  4000000,  3470771,  3000000,  2636696,  2323080,
        2216400,  1800000,  1345800,   770610,   770610,   687456,
         358107,   251272, 11000000,  9000000,  8275862,  7140000,
        4500000,  2900000,  2497320,  1709280,  1634000,  1446720,
        1262520,   797581,   711517,   711517,   442114,   442114,
         442114,   422725, 11000000,  9000000,  8937931,  4140000,
        3100000,  2710560,  1837560,  1600000,  1000497,   855189,
         825497,   825497,   736420,   632455,   118435,    17328,
       11000000, 10800000,  9000000,  6883800,  4447792,  3540000,
        3065040,  2913840,  2225000,  1254720,   855189,   854389,
         825497,   825497,   762195,   762195,   473604,   133723,
       11610000,  9000000,  6750000,  4099920,  3823000,  3117120,
        2956658,  2126520,  1027424,   855189,   854389,   854389,
         854389,   825497,   785487,   650000,   633253,   473604,
         473604,   211084,    75793, 13000000, 12744000, 10164000,
        9000000,  5400000,  4099920,  4000000,  4000000,  3958742,
        2798040,  2222160,  1020960,   884293,   854389,   854389,
         854389,   850000,   825497,   762195,   633253,   473604,
         211084,    75793, 14000000, 13878000, 12868632,  9887642,
        3500000,  2923920,  2317920,  2162419,  2000000,  1056720,
         875500,   660619,   490180, 15012000, 12972973, 12289544,
       10629213,  5305000,  3657500,  3075880,  3049920,  1145685,
        1145685,  1112880,  1104240,   915243,   915243,   816482,
         816482,   816482,   167122, 15501000, 14260870, 13800000,
       11710456, 11370786,  5543725,  3873398,  3815000,  2500000,
        2008748,  1270964,  1131960,   947276,   947276,   845059,
         289755, 26540100, 16663575, 15330435, 12112359, 11131368,
        5782450,  2898000,  1403611,  1182840,  1171560,   980431,
         980431,   980431,   980431,   980431,   980431,   980431,
         543471,   543471,   543471,   543471,   543471, 37457154,
       17826150, 17469565, 14814815,  7692308,  5192000,  3477600,
        1544951,  1471382,  1471382,  1471382,  1471382,  1378242,
        1312611,  1312611,  1312611,  1312611,   980431,   980431,
         980431,   980431,   815615,   543471,   543471,   543471,
         543471, 37457154, 30000000, 18988725, 17469565, 16000000,
        8307692,  5337000,  1644240,  1544951,  1544951,  1512601,
        1512601,  1378242,  1349383,   307648, 40231758, 32742000,
       18539130,  4464226,  2177483,  1964760,  1897800,   898310,
         898310,   842327,   654469,   350189,   350189])

In [7]:
type(salary_col)

numpy.ndarray

In [8]:
#np.average(salary_select)
# can't call numpy function on tables

In [9]:
np.average(salary_col)

4315935.9228295824

## Practice

Find the total salary paid to Chicago Bulls players in the year 2010.
- Use where to narrow the table to the right team and year.
- Use column to extract the correct column as an array.
- Use the sum command on the array.

In [10]:
bulls = nba.where('team', 'Chicago Bulls')
bulls2010 = bulls.where('season', 2010)
#bulls2010.show()
salary_arr = bulls2010.column('salary')
np.average(salary_arr)

3476431.9411764704

## with_column

In [11]:
nba = Table.read_table('nba_salaries.csv')
warriors = nba.where('team', 'Golden State Warriors')
warriors.show(10)

In [12]:
salary_dollars = warriors.column('salary')
salary_euros = np.round(0.86 * salary_dollars)
salary_euros

array([  4.51500000e+06,   4.28968000e+06,   3.61200000e+06,
         3.61200000e+06,   3.38582000e+06,   2.23600000e+06,
         2.15258000e+06,   4.82546000e+06,   4.12800000e+06,
         4.12800000e+06,   3.77196000e+06,   3.07708000e+06,
         2.91540000e+06,   2.30308000e+06,   1.58412000e+06,
         6.51020000e+05,   2.71760000e+05,   2.71760000e+05,
         2.07260000e+05,   2.75200000e+04,   5.36210000e+06,
         4.64400000e+06,   4.64400000e+06,   4.22518000e+06,
         3.81926000e+06,   3.78400000e+06,   2.91368000e+06,
         2.58000000e+06,   2.01498000e+06,   1.73806000e+06,
         1.12660000e+06,   2.86380000e+05,   2.86380000e+05,
         5.89788000e+06,   5.16000000e+06,   4.76440000e+06,
         4.24410000e+06,   3.84334000e+06,   3.78400000e+06,
         1.21174000e+06,   6.02000000e+05,   4.40320000e+05,
         9.38432000e+06,   6.43452000e+06,   4.68270000e+06,
         3.78400000e+06,   1.43362000e+06,   1.29602000e+06,
         2.58000000e+06,   2.13366000e+06,   2.05540000e+06,
         1.91952000e+06,   1.17820000e+07,   7.64444400e+06,
         6.33396800e+06,   6.28875000e+06,   4.63823800e+06,
         3.87538400e+06,   1.70981800e+06,   1.64304700e+06,
         1.59733000e+06,   1.51360000e+06,   1.20775000e+06,
         3.85935000e+05,   3.64435000e+05,   1.29602000e+07,
         8.59999900e+06,   6.98750000e+06,   2.18032400e+06,
         1.85510300e+06,   1.77307900e+06,   1.70878600e+06,
         6.86376000e+05,   6.40314000e+05,   5.71220000e+05,
         2.23402000e+05,   1.41384000e+07,   7.24603800e+06,
         5.70180000e+06,   3.44000000e+06,   2.98486300e+06,
         2.58000000e+06,   2.26755900e+06,   1.99784900e+06,
         1.90610400e+06,   1.54800000e+06,   1.15738800e+06,
         6.62725000e+05,   6.62725000e+05,   5.91212000e+05,
         3.07972000e+05,   2.16094000e+05,   9.46000000e+06,
         7.74000000e+06,   7.11724100e+06,   6.14040000e+06,
         3.87000000e+06,   2.49400000e+06,   2.14769500e+06,
         1.46998100e+06,   1.40524000e+06,   1.24417900e+06,
         1.08576700e+06,   6.85920000e+05,   6.11905000e+05,
         6.11905000e+05,   3.80218000e+05,   3.80218000e+05,
         3.80218000e+05,   3.63544000e+05,   9.46000000e+06,
         7.74000000e+06,   7.68662100e+06,   3.56040000e+06,
         2.66600000e+06,   2.33108200e+06,   1.58030200e+06,
         1.37600000e+06,   8.60427000e+05,   7.35463000e+05,
         7.09927000e+05,   7.09927000e+05,   6.33321000e+05,
         5.43911000e+05,   1.01854000e+05,   1.49020000e+04,
         9.46000000e+06,   9.28800000e+06,   7.74000000e+06,
         5.92006800e+06,   3.82510100e+06,   3.04440000e+06,
         2.63593400e+06,   2.50590200e+06,   1.91350000e+06,
         1.07905900e+06,   7.35463000e+05,   7.34775000e+05,
         7.09927000e+05,   7.09927000e+05,   6.55488000e+05,
         6.55488000e+05,   4.07299000e+05,   1.15002000e+05,
         9.98460000e+06,   7.74000000e+06,   5.80500000e+06,
         3.52593100e+06,   3.28778000e+06,   2.68072300e+06,
         2.54272600e+06,   1.82880700e+06,   8.83585000e+05,
         7.35463000e+05,   7.34775000e+05,   7.34775000e+05,
         7.34775000e+05,   7.09927000e+05,   6.75519000e+05,
         5.59000000e+05,   5.44598000e+05,   4.07299000e+05,
         4.07299000e+05,   1.81532000e+05,   6.51820000e+04,
         1.11800000e+07,   1.09598400e+07,   8.74104000e+06,
         7.74000000e+06,   4.64400000e+06,   3.52593100e+06,
         3.44000000e+06,   3.44000000e+06,   3.40451800e+06,
         2.40631400e+06,   1.91105800e+06,   8.78026000e+05,
         7.60492000e+05,   7.34775000e+05,   7.34775000e+05,
         7.34775000e+05,   7.31000000e+05,   7.09927000e+05,
         6.55488000e+05,   5.44598000e+05,   4.07299000e+05,
         1.81532000e+05,   6.51820000e+04,   1.20400000e+07,
         1.19350800e+07,   1.10670240e+07,   8.50337200e+06,
         3.01000000e+06,   2.51457100e+06,   1.99341100e+06,
         1.85968000e+06,   1.72000000e+06,   9.08779000e+05,
         7.52930000e+05,   5.68132000e+05,   4.21555000e+05,
         1.29103200e+07,   1.11567570e+07,   1.05690080e+07,
         9.14112300e+06,   4.56230000e+06,   3.14545000e+06,
         2.64525700e+06,   2.62293100e+06,   9.85289000e+05,
         9.85289000e+05,   9.57077000e+05,   9.49646000e+05,
         7.87109000e+05,   7.87109000e+05,   7.02175000e+05,
         7.02175000e+05,   7.02175000e+05,   1.43725000e+05,
         1.33308600e+07,   1.22643480e+07,   1.18680000e+07,
         1.00709920e+07,   9.77887600e+06,   4.76760400e+06,
         3.33112200e+06,   3.28090000e+06,   2.15000000e+06,
         1.72752300e+06,   1.09302900e+06,   9.73486000e+05,
         8.14657000e+05,   8.14657000e+05,   7.26751000e+05,
         2.49189000e+05,   2.28244860e+07,   1.43306740e+07,
         1.31841740e+07,   1.04166290e+07,   9.57297600e+06,
         4.97290700e+06,   2.49228000e+06,   1.20710500e+06,
         1.01724200e+06,   1.00754200e+06,   8.43171000e+05,
         8.43171000e+05,   8.43171000e+05,   8.43171000e+05,
         8.43171000e+05,   8.43171000e+05,   8.43171000e+05,
         4.67385000e+05,   4.67385000e+05,   4.67385000e+05,
         4.67385000e+05,   4.67385000e+05,   3.22131520e+07,
         1.53304890e+07,   1.50238260e+07,   1.27407410e+07,
         6.61538500e+06,   4.46512000e+06,   2.99073600e+06,
         1.32865800e+06,   1.26538900e+06,   1.26538900e+06,
         1.26538900e+06,   1.26538900e+06,   1.18528800e+06,
         1.12884500e+06,   1.12884500e+06,   1.12884500e+06,
         1.12884500e+06,   8.43171000e+05,   8.43171000e+05,
         8.43171000e+05,   8.43171000e+05,   7.01429000e+05,
         4.67385000e+05,   4.67385000e+05,   4.67385000e+05,
         4.67385000e+05,   3.22131520e+07,   2.58000000e+07,
         1.63303040e+07,   1.50238260e+07,   1.37600000e+07,
         7.14461500e+06,   4.58982000e+06,   1.41404600e+06,
         1.32865800e+06,   1.32865800e+06,   1.30083700e+06,
         1.30083700e+06,   1.18528800e+06,   1.16046900e+06,
         2.64577000e+05,   3.45993120e+07,   2.81581200e+07,
         1.59436520e+07,   3.83923400e+06,   1.87263500e+06,
         1.68969400e+06,   1.63210800e+06,   7.72547000e+05,
         7.72547000e+05,   7.24401000e+05,   5.62843000e+05,
         3.01163000e+05,   3.01163000e+05])

In [13]:
# Attach new column to table
warriors = warriors.with_column('salary euros', salary_euros)
warriors.show(10) # salaries turned from into to float, but that's okay