In [2]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

In [3]:
survey = Table.read_table('welcome_survey_sp24.csv')
survey.show(10)

## Pivot Tables

In [4]:
# Previously saw how to classify by multiple variables using the group command
survey.group(['Handedness', 'Sleep position'])

Handedness                                              | Sleep position     | count
Ambidexterous                                           | On your stomach    | 1
Ambidextrous                                            | On your back       | 1
Ambidextrous                                            | On your stomach    | 1
Cross-dominant                                          | On your back       | 1
I can write with both but my right hand is much better. | On your right side | 1
Left-handed                                             | On your back       | 23
Left-handed                                             | On your left side  | 24
Left-handed                                             | On your right side | 14
Left-handed                                             | On your stomach    | 8
Right-handed                                            | On your back       | 220
... (6 rows omitted)

In [5]:
# pivot tables are more visually helpful when you have exactly two variables
# Create a new table where:
# Columns are all the different values in the "Handedness" column of the original table
# Rows are all the different values in the "Sleep position" column of the original table
# The entry is the number of people who answered that combination of "Handedness" and "Sleep position"
survey.pivot("Handedness", "Sleep position")

Sleep position     | Ambidexterous | Ambidextrous | Cross-dominant | I can write with both but my right hand is much better. | Left-handed | Right-handed | ambidextrous | both
On your back       | 0             | 1            | 1              | 0                                                       | 23          | 220          | 1            | 0
On your left side  | 0             | 0            | 0              | 0                                                       | 24          | 226          | 0            | 1
On your right side | 0             | 0            | 0              | 1                                                       | 14          | 294          | 1            | 0
On your stomach    | 1             | 1            | 0              | 0                                                       | 8           | 115          | 0            | 0

In [6]:
# Similar to the group command, you can specify a characteristic to record in the cell other than the count
# This example records the minimum value of "Number of textees" for each of the pivot categories
survey.pivot("Handedness", "Sleep position", values = "Number of textees", collect = np.average)

Sleep position     | Ambidexterous | Ambidextrous | Cross-dominant | I can write with both but my right hand is much better. | Left-handed | Right-handed | ambidextrous | both
On your back       | 0             | 15           | 2              | 0                                                       | 6.65217     | 6.50909      | 10           | 0
On your left side  | 0             | 0            | 0              | 0                                                       | 9.70833     | 6.34956      | 0            | 4
On your right side | 0             | 0            | 0              | 8                                                       | 4.85714     | 6.65986      | 10           | 0
On your stomach    | 9             | 7            | 0              | 0                                                       | 6.875       | 8.64348      | 0            | 0

# Practice

In [7]:
# From the CORGIS Dataset Project
# By Austin Cory Bart acbart@vt.edu
# Version 2.0.0, created 3/22/2016
# https://corgis-edu.github.io/corgis/csv/skyscrapers/

sky = Table.read_table('skyscrapers.csv')
sky.show(3)

1. For each city, find the number of skyscrapers of each type of material.
2. For each city, find the tallest skyscraper of each type of material. (Add a third column and collect function.)

In [8]:
material = sky.pivot('city', 'material')
material

material        | Atlanta | Austin | Baltimore | Boston | Charlotte | Chicago | Cincinnati | Cleveland | Columbus | Dallas | Denver | Detroit | Honolulu | Houston | Indianapolis | Jersey City | Kansas City | Las Vegas | Los Angeles | Miami | Miami Beach | Milwaukee | Minneapolis | New York City | Philadelphia | Phoenix | Pittsburgh | Portland | Sacramento | Salt Lake City | San Diego | San Francisco | Seattle | St. Louis | Sunny Isles Beach
concrete        | 27      | 16     | 8         | 4      | 5         | 244     | 5          | 2         | 4        | 7      | 5      | 6       | 47       | 27      | 9            | 14          | 3           | 33        | 9           | 78    | 19          | 9         | 18          | 249           | 14           | 7       | 2          | 4        | 3          | 6              | 11        | 10            | 14      | 6         | 22
mixed/composite | 4       | 0      | 0         | 2      | 3         | 35      | 1          | 3         | 0        | 2      | 2      | 0       | 0        | 7       | 0            | 0           | 0           | 6         | 3           | 4     | 0           | 0         | 9           | 19            | 2            | 4       | 2          | 1        | 1          | 0              | 1         | 3             | 9       | 1         | 0
steel           | 7       | 1      | 6         | 26     | 4         | 79      | 7          | 11        | 9        | 11     | 4      | 14      | 3        | 20      | 7            | 2           | 7           | 5         | 37          | 4     | 0           | 5         | 12          | 263           | 15           | 4       | 32         | 5        | 7          | 7              | 9         | 48            | 31      | 8         | 0

## Joins

In [9]:
sky.pivot('city', 'material', values ='height', collect = max)

material        | Atlanta | Austin | Baltimore | Boston | Charlotte | Chicago | Cincinnati | Cleveland | Columbus | Dallas | Denver | Detroit | Honolulu | Houston | Indianapolis | Jersey City | Kansas City | Las Vegas | Los Angeles | Miami  | Miami Beach | Milwaukee | Minneapolis | New York City | Philadelphia | Phoenix | Pittsburgh | Portland | Sacramento | Salt Lake City | San Diego | San Francisco | Seattle | St. Louis | Sunny Isles Beach
concrete        | 264.25  | 208.15 | 161.24    | 121.92 | 265.48    | 423.22  | 125        | 125       | 79.25    | 176.48 | 194.75 | 221.49  | 129.8    | 217.63  | 128.17       | 162.16      | 189.89      | 350.22    | 145.7       | 240.41 | 170.39      | 136       | 203.58      | 425.5         | 157.89       | 124.1   | 89.3       | 155.15   | 106.98     | 114.91         | 151.49    | 196.6         | 138.69  | 100.66    | 196
mixed/composite | 311.8   | 0      | 0         | 139    | 239.7     | 306.94  | 202.69     | 288.65    | 0        | 280.72 | 212.75 | 0       | 0        | 305.41  | 0            | 0           | 0           | 195.68    | 118.26      | 232.8  | 0           | 0         | 241.38      | 541.3         | 296.73       | 114     | 172        | 127.4    | 115.82     | 0              | 144.78    | 260           | 284.38  | 180.75    | 0
steel           | 169.47  | 93.6   | 155.15    | 240.79 | 179.23    | 442.14  | 175        | 215.8     | 169.3    | 270.06 | 217.63 | 173.26  | 130.75   | 302.37  | 213.67       | 238.05      | 146.61      | 164.6     | 310.29      | 147.52 | 0           | 183.19    | 144.64      | 381           | 288.04       | 147.22  | 256.34     | 166.42   | 122.6      | 128.63         | 152.4     | 237.44        | 235.31  | 147.6     | 0

In [10]:
drinks = Table(['Drink', 'Cafe', 'Price'])
drinks = drinks.with_rows([
    ['Milk Tea', 'Asha', 5.5],
    ['Espresso', 'Strada',  1.75],
    ['Latte',    'Strada',  3.25],
    ['Espresso', "FSM",   2]
])
drinks

Drink    | Cafe   | Price
Milk Tea | Asha   | 5.5
Espresso | Strada | 1.75
Latte    | Strada | 3.25
Espresso | FSM    | 2

In [11]:
discounts = Table().with_columns(
    'Coupon % off', make_array(10, 25, 5),
    'Location', make_array('Asha', 'Strada', 'FSM')
)
discounts

Coupon % off | Location
10           | Asha
25           | Strada
5            | FSM

In [12]:
# In the drinks table, the name of the cafe is in the column 'Cafe'
# In the discounts table, this same name appears in the column 'Location'
# We can join these tables by matching up the entries in these two columns
combined = drinks.join('Cafe', discounts, 'Location')
combined

Cafe   | Drink    | Price | Coupon % off
Asha   | Milk Tea | 5.5   | 10
FSM    | Espresso | 2     | 5
Strada | Espresso | 1.75  | 25
Strada | Latte    | 3.25  | 25

In [16]:
prices = combined.column('Price')
discounts = combined.column('Coupon % off')
discounted_prices = prices * (1- discounts /100)
combined = combined.with_column('Discounted Price', discounted_prices)
combined

Cafe   | Drink    | Price | Coupon % off | Discounted Price
Asha   | Milk Tea | 5.5   | 10           | 4.95
FSM    | Espresso | 2     | 5            | 1.9
Strada | Espresso | 1.75  | 25           | 1.3125
Strada | Latte    | 3.25  | 25           | 2.4375

# Practice
Join the toppings table to the cones table so that the suggested topping appears in each row of cones.

In [13]:
cones = Table.read_table('cones.csv')
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

In [14]:
toppings = Table(['Ice Cream', 'Topping'])
toppings = toppings.with_rows([
    ['strawberry', 'marshmallow'],
    ['chocolate', 'caramel'],
    ['bubblegum', 'sprinkles']
])
toppings

Ice Cream  | Topping
strawberry | marshmallow
chocolate  | caramel
bubblegum  | sprinkles

In [20]:
combined = cones.join('Flavor', toppings, 'Ice Cream')
combined

Flavor     | Color       | Price | Topping
bubblegum  | pink        | 4.75  | sprinkles
chocolate  | light brown | 4.75  | caramel
chocolate  | dark brown  | 5.25  | caramel
chocolate  | dark brown  | 5.25  | caramel
strawberry | pink        | 3.55  | marshmallow
strawberry | pink        | 5.25  | marshmallow