# Classifying

In [2]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

In [3]:
cones = Table().with_columns(
    'Flavor', make_array('strawberry', 'chocolate', 'chocolate', 'strawberry', 'chocolate'),
    'Price', make_array(3.55, 4.75, 6.55, 5.25, 5.25)
)
cones

Flavor     | Price
strawberry | 3.55
chocolate  | 4.75
chocolate  | 6.55
strawberry | 5.25
chocolate  | 5.25

In [4]:
# Default behavior is to count the number of 
# occurrences of each category
cones.group('Flavor')

Flavor     | count
chocolate  | 3
strawberry | 2

In [5]:
# Optionally, you can specify any function you want to see a different 
# characteristic of the categories.
# This computes the most expensive ice cream in each category
cones.group('Flavor', max)

Flavor     | Price max
chocolate  | 6.55
strawberry | 5.25

In [6]:
# This computes the average of all prices in the category
cones.group('Flavor', np.average)

Flavor     | Price average
chocolate  | 5.51667
strawberry | 4.4

In [8]:
nba = Table.read_table('nba_salaries.csv')
nba

rank | name             | position | team                   | salary   | season
1    | Shaquille O'Neal | C        | Los Angeles Lakers     | 17142000 | 2000
2    | Kevin Garnett    | PF       | Minnesota Timberwolves | 16806000 | 2000
3    | Alonzo Mourning  | C        | Miami Heat             | 15004000 | 2000
4    | Juwan Howard     | PF       | Washington Wizards     | 15000000 | 2000
5    | Scottie Pippen   | SF       | Portland Trail Blazers | 14795000 | 2000
6    | Karl Malone      | PF       | Utah Jazz              | 14000000 | 2000
7    | Larry Johnson    | F        | New York Knicks        | 11910000 | 2000
8    | Gary Payton      | PG       | Seattle SuperSonics    | 11020000 | 2000
9    | Rasheed Wallace  | PF       | Portland Trail Blazers | 10800000 | 2000
10   | Shawn Kemp       | C        | Cleveland Cavaliers    | 10780000 | 2000
... (9446 rows omitted)

# Practice 1
Find the total amount of money each team paid out in salaries in the year 2000.
- Select only the rows pertaining to the year 2000.
- Select only the columns relevant to your calculation.
- Group in such a way that computes the requested.

In [28]:
year2000 = nba.where("season", 2000)
year2000 = year2000.select('team', 'salary')
salarybyteams = year2000.group('team', sum)
salarybyteams.show()

# Practice 2
Find the average salary earned by players in each position in the year 2000. (For example, the row with position 'C' contains the average salary paid to all centers across all teams in the year 2000.)

In [31]:
year_2000 = nba.where('season', 2000)
year_2000 = year_2000.select('position', 'salary')
positiongrouped = year_2000.group('position', np.average)
positiongrouped

position | salary average
C        | 5.49811e+06
F        | 3.26657e+06
G        | 2.21267e+06
PF       | 5.24797e+06
PG       | 4.79082e+06
SF       | 3.61327e+06
SG       | 3.11245e+06

# Classifying by multiple variables

In [32]:
more_cones = Table().with_columns(
    'Flavor', make_array('strawberry', 'chocolate', 'chocolate', 'strawberry', 'chocolate', 'bubblegum'),
    'Color', make_array('pink', 'light brown', 'dark brown', 'pink', 'dark brown', 'pink'),
    'Price', make_array(3.55, 4.75, 5.25, 5.25, 5.25, 4.75)
)

more_cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

In [33]:
# Can provide a list of multiple categories to group by
more_cones.group(['Flavor', 'Color'])

Flavor     | Color       | count
bubblegum  | pink        | 1
chocolate  | dark brown  | 2
chocolate  | light brown | 1
strawberry | pink        | 2

In [10]:
# Just like with a single variable, you can provide 
# a function to look at a different characteristic
more_cones.group(['Flavor', 'Color'], max)

Flavor     | Color       | Price max
bubblegum  | pink        | 4.75
chocolate  | dark brown  | 5.25
chocolate  | light brown | 4.75
strawberry | pink        | 5.25

# Practice 3
Find the total paid in salaries by each team *during each season*. 

- Select the columns relevant to your calculation.
- Group by multiple columns in such a way that the sum is returned.

In [39]:
new = nba.select('team', 'season', 'salary')
grouped = new.group(['team', 'season'], sum)
grouped

team          | season | salary sum
Atlanta Hawks | 2000   | 16018000
Atlanta Hawks | 2001   | 19721000
Atlanta Hawks | 2002   | 49862000
Atlanta Hawks | 2003   | 54529000
Atlanta Hawks | 2004   | 15724000
Atlanta Hawks | 2005   | 10899000
Atlanta Hawks | 2006   | 38198405
Atlanta Hawks | 2007   | 45084224
Atlanta Hawks | 2008   | 38116186
Atlanta Hawks | 2009   | 68992109
... (648 rows omitted)